---
# tasks file for semodule

- name: Install required packages for managing SELinux
  yum:
    name: "{{ item }}"
    state: installed
  with_items:
    - checkpolicy
    - policycoreutils-python
  when: ansible_os_family == "RedHat"


- name: Deploy semodule loop
  include_tasks: "setup_semodule.yml"
  with_list: "{{ semodule_semodules }}"
  loop_control:
    loop_var: semodule

# - name: Copy type enforcement files
#   copy:
#     dest: "{{ semodule_file_type_enforcement_dest }}"
#     src: "{{ item }}"
#   register: results
#   with_items: "{{ semodule_te_items }}"
#   when: ansible_os_family == "RedHat"



# - name: checkmodule
#   shell: "checkmodule -M -m -o {{ item.item|basename|replace('.te', '.mod') }} {{ item.item|basename }}"
#   args:
#     chdir: "{{ semodule_file_type_enforcement_dest }}"
#   when: item.changed and ( ansible_os_family == "RedHat" )
#   with_items: "{{ results.results }}"
#
#
# - name: semodule_package
#   shell: "semodule_package -o {{ item.item|basename|replace('.te', '.pp') }} -m {{ item.item|basename|replace('.te', '.mod') }}"
#   args:
#     chdir: "{{ semodule_file_type_enforcement_dest }}"
#   when: item.changed and ( ansible_os_family == "RedHat" )
#   with_items: "{{ results.results }}"
#
# - name: semodule
#   shell: "semodule -i {{ item.item|basename|replace('.te', '.pp') }}"
#   args:
#     chdir: "{{ semodule_file_type_enforcement_dest }}"
#   when: item.changed and ( ansible_os_family == "RedHat" )
#   with_items: "{{ results.results }}"
