---
# tasks file for selinux

- name: Install required packages for managing SELinux
  yum:
    name: "{{ item }}"
    state: installed
  with_items:
    - checkpolicy
    - policycoreutils-python
  when: ansible_os_family == "RedHat"

- name: Deploy semodule loop
  include_tasks: "setup_semodule.yml"
  with_list: "{{ selinux_semodules }}"
  loop_control:
    loop_var: semodule

- name: Configure selinux booleans
  seboolean:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
    persistent: "{{ item.persistent | default('yes') }}"
  with_items: "{{ selinux_booleans }}"
