- name: Creates type enforcement files
  copy:
    dest: "{{ selinux_file_type_enforcement_dest }}{{ semodule.name }}"
    content: "{{ semodule.module }}"
    owner: root
    group: root
    mode: 0600
  register: type_enforcement_file_results
  when: ansible_os_family == "RedHat"


- name: checkmodule
  shell: "checkmodule -M -m -o {{ semodule.name|basename|replace('.te', '.mod') }} {{ semodule.name|basename }}"
  args:
    chdir: "{{ selinux_file_type_enforcement_dest }}"
  when:
    - type_enforcement_file_results.changed
    - ansible_os_family == "RedHat"


- name: semodule_package
  shell: "semodule_package -o {{ semodule.name|basename|replace('.te', '.pp') }} -m {{ semodule.name|basename|replace('.te', '.mod') }}"
  args:
    chdir: "{{ selinux_file_type_enforcement_dest }}"
  when:
    - type_enforcement_file_results.changed
    - ansible_os_family == "RedHat"

- name: semodule
  shell: "semodule -i {{ semodule.name|basename|replace('.te', '.pp') }}"
  args:
    chdir: "{{ selinux_file_type_enforcement_dest }}"
  when:
    - type_enforcement_file_results.changed
    - ansible_os_family == "RedHat"
